spring.application.name=Ecommerce Product Catlog

spring.datasource.url=jdbc:mysql://localhost:3306/productcatlog
spring.datasource.username=root
spring.datasource.password=${DB_Password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

